/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.CdcClientes;
import dao.ClientesDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;




/**
 *
 * @author clari
 */
public class Cdc_JDlgClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDialogClientes
     */
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean incluir;
    boolean pesquisando = false;
    private MaskFormatter mascaraCpf;
    
    public Cdc_JDlgClientes(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setTitle("Cadastro de Clientes");
    setLocationRelativeTo(null);
    Util.habilitar(false, cdc_jTxtCodigo, cdc_jFmtcpf, cdc_jTxtEmail, cdc_jTxtEndereco, cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtNome, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado, cdc_jCBoxAtivo, 
                   cdc_jBtnConfirmar, cdc_jBtnCancelar);
    try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            cdc_jFmtcpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        } catch (ParseException ex) {
            Logger.getLogger(Cdc_jDlgUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
            public CdcClientes viewBean() {
                CdcClientes clientes = new CdcClientes();
                int codigo = Util.strToInt(cdc_jTxtCodigo.getText());
                clientes.setCdcIdClientes(codigo);
                clientes.setCdcNome(cdc_jTxtNome.getText());
                clientes.setCdcCpf(cdc_jFmtcpf.getText());
                clientes.setCdcRg(cdc_jTxtRg.getText());
                clientes.setCdcSexo(cdc_jTxtSexo.getText());
                clientes.setCdcDataNas(Util.strToDate(cdc_jFmtdataNasc.getText()));      
                clientes.setCdcEmail(cdc_jTxtEmail.getText());
                clientes.setCdcCep(cdc_jTxtCep.getText());
                clientes.setCdcEndereco(cdc_jTxtEndereco.getText());
                clientes.setCdcBairro(cdc_jTxtBairro.getText());
                clientes.setCdcEstado(cdc_jTxtEstado.getText());
                clientes.setCdcCidade(cdc_jTxtCidade.getText());
                clientes.setCdcTelefone(cdc_jTxtTelefone.getText());
                clientes.setCdcCelular(cdc_jTxtCelular.getText());
                if (cdc_jCBoxAtivo.isSelected() == true) {
                    clientes.setCdcAtivo("S");
                } else {
                    clientes.setCdcAtivo("N");
                }
                return clientes;
}

            public void beanView(CdcClientes clientes) {
                cdc_jTxtCodigo.setText(Util.intToStr(clientes.getCdcIdClientes()));
                cdc_jTxtNome.setText(clientes.getCdcNome());
                cdc_jFmtcpf.setText(clientes.getCdcCpf());
                cdc_jTxtRg.setText(clientes.getCdcRg());
                cdc_jTxtSexo.setText(clientes.getCdcSexo());
               cdc_jFmtdataNasc.setText(Util.dateToStr(clientes.getCdcDataNas()));
                cdc_jTxtEmail.setText(clientes.getCdcEmail());
                cdc_jTxtCep.setText(clientes.getCdcCep());
                cdc_jTxtEndereco.setText(clientes.getCdcEndereco());
                cdc_jTxtBairro.setText(clientes.getCdcBairro());
                cdc_jTxtEstado.setText(clientes.getCdcEstado());
                cdc_jTxtCidade.setText(clientes.getCdcCidade());
                cdc_jTxtTelefone.setText(clientes.getCdcTelefone());
                cdc_jTxtCelular.setText(clientes.getCdcCelular());
                if (clientes.getCdcAtivo().equals("S") == true) {
                    cdc_jCBoxAtivo.setSelected(true);
                } else {
                    cdc_jCBoxAtivo.setSelected(false);
                }

            }
           




    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cdc_jLblNome = new javax.swing.JLabel();
        cdc_jTxtNome = new javax.swing.JTextField();
        cdc_jLblCpf = new javax.swing.JLabel();
        cdc_jLblCodigo = new javax.swing.JLabel();
        cdc_jTxtCodigo = new javax.swing.JTextField();
        cdc_jLblRg = new javax.swing.JLabel();
        cdc_jTxtRg = new javax.swing.JTextField();
        cdc_jLblSexo = new javax.swing.JLabel();
        cdc_jTxtSexo = new javax.swing.JTextField();
        cdc_jLblDataNasc = new javax.swing.JLabel();
        cdc_jLblEmail = new javax.swing.JLabel();
        cdc_jTxtEmail = new javax.swing.JTextField();
        cdc_jLblEnderoco = new javax.swing.JLabel();
        cdc_jTxtEndereco = new javax.swing.JTextField();
        cdc_jLblCep = new javax.swing.JLabel();
        cdc_jTxtCep = new javax.swing.JTextField();
        cdc_jLblBairro = new javax.swing.JLabel();
        cdc_jTxtBairro = new javax.swing.JTextField();
        cdc_jLblEstado = new javax.swing.JLabel();
        cdc_jTxtEstado = new javax.swing.JTextField();
        cdc_jLblCidade = new javax.swing.JLabel();
        cdc_jTxtCidade = new javax.swing.JTextField();
        cdc_jLblTelefone = new javax.swing.JLabel();
        cdc_jTxtTelefone = new javax.swing.JTextField();
        cdc_jLblCelular = new javax.swing.JLabel();
        cdc_jTxtCelular = new javax.swing.JTextField();
        cdc_jLblAtivo = new javax.swing.JLabel();
        cdc_jBtnIncluir = new javax.swing.JButton();
        cdc_jBtnAlterar = new javax.swing.JButton();
        cdc_jBtnExcluir = new javax.swing.JButton();
        cdc_jBtnConfirmar = new javax.swing.JButton();
        cdc_jBtnCancelar = new javax.swing.JButton();
        cdc_jbtnPesquisar = new javax.swing.JButton();
        cdc_jCBoxAtivo = new javax.swing.JCheckBox();
        cdc_jFmtdataNasc = new javax.swing.JFormattedTextField();
        cdc_jFmtcpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cdc_jLblNome.setText("Nome");

        cdc_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtNomeActionPerformed(evt);
            }
        });

        cdc_jLblCpf.setText("CPF");

        cdc_jLblCodigo.setText("Código");

        cdc_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtCodigoActionPerformed(evt);
            }
        });

        cdc_jLblRg.setText("RG");

        cdc_jTxtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtRgActionPerformed(evt);
            }
        });

        cdc_jLblSexo.setText("Sexo");

        cdc_jTxtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtSexoActionPerformed(evt);
            }
        });

        cdc_jLblDataNasc.setText("Data de Nascimento");

        cdc_jLblEmail.setText("Email");

        cdc_jLblEnderoco.setText("Endereço");

        cdc_jTxtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtEnderecoActionPerformed(evt);
            }
        });

        cdc_jLblCep.setText("CEP");

        cdc_jLblBairro.setText("Bairro");

        cdc_jLblEstado.setText("Estado");

        cdc_jLblCidade.setText("Cidade");

        cdc_jLblTelefone.setText("Telefone");

        cdc_jLblCelular.setText("Celular");

        cdc_jLblAtivo.setText("Ativo");

        cdc_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        cdc_jBtnIncluir.setText("Incluir");
        cdc_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirActionPerformed(evt);
            }
        });

        cdc_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        cdc_jBtnAlterar.setText("Alterar");
        cdc_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnAlterarActionPerformed(evt);
            }
        });

        cdc_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        cdc_jBtnExcluir.setText("Excluir");
        cdc_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnExcluirActionPerformed(evt);
            }
        });

        cdc_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        cdc_jBtnConfirmar.setText("Confirmar");
        cdc_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnConfirmarActionPerformed(evt);
            }
        });

        cdc_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        cdc_jBtnCancelar.setText("Cancelar");
        cdc_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnCancelarActionPerformed(evt);
            }
        });

        cdc_jbtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        cdc_jbtnPesquisar.setText("Pesquisar");
        cdc_jbtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jbtnPesquisarActionPerformed(evt);
            }
        });

        cdc_jCBoxAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jCBoxAtivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cdc_jLblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cdc_jTxtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cdc_jLblEnderoco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jLblCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jLblCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jLblBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jTxtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                    .addComponent(cdc_jTxtBairro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cdc_jTxtCelular, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(cdc_jFmtcpf, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cdc_jLblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jLblRg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jLblDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jLblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jFmtdataNasc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cdc_jLblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)
                                                .addComponent(cdc_jLblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cdc_jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cdc_jTxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(cdc_jLblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cdc_jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cdc_jLblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cdc_jCBoxAtivo))))
                                    .addComponent(cdc_jTxtRg)
                                    .addComponent(cdc_jTxtCidade)
                                    .addComponent(cdc_jTxtCep)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(cdc_jTxtNome)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cdc_jLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cdc_jLblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cdc_jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cdc_jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jbtnPesquisar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jLblCodigo)
                    .addComponent(cdc_jLblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdc_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cdc_jLblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jFmtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cdc_jLblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cdc_jLblEnderoco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cdc_jLblBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cdc_jLblCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jTxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cdc_jLblRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jTxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cdc_jLblDataNasc)
                        .addGap(12, 12, 12)
                        .addComponent(cdc_jFmtdataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cdc_jLblCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jTxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cdc_jLblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cdc_jLblTelefone)
                                    .addComponent(cdc_jLblAtivo)
                                    .addComponent(cdc_jLblSexo)
                                    .addComponent(cdc_jLblEstado))
                                .addGap(7, 7, 7)
                                .addComponent(cdc_jCBoxAtivo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cdc_jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cdc_jTxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cdc_jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jBtnIncluir)
                    .addComponent(cdc_jBtnAlterar)
                    .addComponent(cdc_jBtnExcluir)
                    .addComponent(cdc_jBtnConfirmar)
                    .addComponent(cdc_jBtnCancelar)
                    .addComponent(cdc_jbtnPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdc_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtNomeActionPerformed

    private void cdc_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtCodigoActionPerformed

    private void cdc_jTxtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtRgActionPerformed

    private void cdc_jTxtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtSexoActionPerformed

    private void cdc_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, cdc_jTxtCodigo, cdc_jFmtcpf, cdc_jTxtEmail, cdc_jTxtEndereco, cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtNome, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado, cdc_jCBoxAtivo, cdc_jBtnConfirmar, cdc_jBtnCancelar);
        Util.habilitar(false, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jbtnPesquisar, cdc_jBtnIncluir);
        Util.limpar(cdc_jTxtCodigo, cdc_jTxtNome, cdc_jTxtEmail, cdc_jTxtEndereco, cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado);
        cdc_jTxtCodigo.grabFocus();
        incluir = true;
       
    }//GEN-LAST:event_cdc_jBtnIncluirActionPerformed

    private void cdc_jbtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jbtnPesquisarActionPerformed
        // TODO add your handling code here:
        Cdc_jDlgClientesPesquisar jDlgClientePesquisar = new Cdc_jDlgClientesPesquisar(null, true);
        jDlgClientePesquisar.setTelaPai(this);
        jDlgClientePesquisar.setVisible(true);
        pesquisando = true;
        
//        }
//      }
    }//GEN-LAST:event_cdc_jbtnPesquisarActionPerformed

    private void cdc_jTxtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtEnderecoActionPerformed

    private void cdc_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        ClientesDAO clientesDAO = new ClientesDAO();
        if (incluir == true) {
            clientesDAO.insert(viewBean());
        } else {
            clientesDAO.update(viewBean());
        }
        Util.habilitar(false, cdc_jTxtCodigo, cdc_jFmtcpf, cdc_jTxtEmail, cdc_jTxtEndereco ,cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtNome, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado, cdc_jCBoxAtivo, cdc_jBtnConfirmar, cdc_jBtnCancelar);
        Util.habilitar(true, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jbtnPesquisar, cdc_jBtnIncluir);
                Util.limpar(cdc_jTxtCodigo, cdc_jTxtNome, cdc_jTxtEmail, cdc_jFmtcpf, cdc_jTxtEndereco, cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado);


         
    }//GEN-LAST:event_cdc_jBtnConfirmarActionPerformed

    private void cdc_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar um usuário primeiro");
        } else {
                if (Util.perguntar("Deseja realmente excluir o registro?")) {
                        ClientesDAO clienteDAO = new ClientesDAO();
                        CdcClientes cliente = viewBean();
                        clienteDAO.delete(cliente);
                Util.limpar(cdc_jTxtCodigo, cdc_jFmtcpf, cdc_jTxtEmail, cdc_jTxtEndereco, cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtNome, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado, cdc_jCBoxAtivo, cdc_jBtnConfirmar, cdc_jBtnCancelar);  
        } 
        }
       
                    
       
    }//GEN-LAST:event_cdc_jBtnExcluirActionPerformed

    private void cdc_jCBoxAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jCBoxAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jCBoxAtivoActionPerformed

    private void cdc_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, cdc_jTxtCodigo, cdc_jFmtcpf, cdc_jTxtEmail, cdc_jTxtEndereco, cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtNome, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado, cdc_jCBoxAtivo, cdc_jBtnConfirmar, cdc_jBtnCancelar);
        Util.habilitar(true, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jbtnPesquisar, cdc_jBtnIncluir);
        Util.limpar(cdc_jTxtCodigo, cdc_jTxtNome, cdc_jTxtEmail, cdc_jTxtEndereco, cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado);


        
    }//GEN-LAST:event_cdc_jBtnCancelarActionPerformed

    private void cdc_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, cdc_jFmtcpf, cdc_jTxtEmail, cdc_jTxtEndereco, cdc_jTxtBairro, cdc_jTxtCelular, cdc_jTxtNome, cdc_jTxtRg, cdc_jFmtdataNasc, cdc_jTxtCep, cdc_jTxtCidade, cdc_jTxtTelefone, cdc_jTxtSexo, cdc_jTxtEstado, cdc_jCBoxAtivo, cdc_jBtnConfirmar, cdc_jBtnCancelar);
        Util.habilitar(false, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jbtnPesquisar, cdc_jBtnIncluir);
        cdc_jTxtNome.grabFocus();
        incluir = false;
        
        
    }//GEN-LAST:event_cdc_jBtnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Cdc_JDlgClientes dialog = new Cdc_JDlgClientes(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdc_jBtnAlterar;
    private javax.swing.JButton cdc_jBtnCancelar;
    private javax.swing.JButton cdc_jBtnConfirmar;
    private javax.swing.JButton cdc_jBtnExcluir;
    private javax.swing.JButton cdc_jBtnIncluir;
    private javax.swing.JCheckBox cdc_jCBoxAtivo;
    private javax.swing.JFormattedTextField cdc_jFmtcpf;
    private javax.swing.JFormattedTextField cdc_jFmtdataNasc;
    private javax.swing.JLabel cdc_jLblAtivo;
    private javax.swing.JLabel cdc_jLblBairro;
    private javax.swing.JLabel cdc_jLblCelular;
    private javax.swing.JLabel cdc_jLblCep;
    private javax.swing.JLabel cdc_jLblCidade;
    private javax.swing.JLabel cdc_jLblCodigo;
    private javax.swing.JLabel cdc_jLblCpf;
    private javax.swing.JLabel cdc_jLblDataNasc;
    private javax.swing.JLabel cdc_jLblEmail;
    private javax.swing.JLabel cdc_jLblEnderoco;
    private javax.swing.JLabel cdc_jLblEstado;
    private javax.swing.JLabel cdc_jLblNome;
    private javax.swing.JLabel cdc_jLblRg;
    private javax.swing.JLabel cdc_jLblSexo;
    private javax.swing.JLabel cdc_jLblTelefone;
    private javax.swing.JTextField cdc_jTxtBairro;
    private javax.swing.JTextField cdc_jTxtCelular;
    private javax.swing.JTextField cdc_jTxtCep;
    private javax.swing.JTextField cdc_jTxtCidade;
    private javax.swing.JTextField cdc_jTxtCodigo;
    private javax.swing.JTextField cdc_jTxtEmail;
    private javax.swing.JTextField cdc_jTxtEndereco;
    private javax.swing.JTextField cdc_jTxtEstado;
    private javax.swing.JTextField cdc_jTxtNome;
    private javax.swing.JTextField cdc_jTxtRg;
    private javax.swing.JTextField cdc_jTxtSexo;
    private javax.swing.JTextField cdc_jTxtTelefone;
    private javax.swing.JButton cdc_jbtnPesquisar;
    // End of variables declaration//GEN-END:variables
}
