/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClientesDAO;
import bean.CdcClientes;
import bean.CdcVendas;
import bean.CdcVendedor;
import dao.Cdc_vendasDAO;
import dao.VendedorDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import tools.Util;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author u1845853
 */
public class Cdc_jDlgVendas extends javax.swing.JDialog {
        private MaskFormatter mascaraDataNasc;
    /**
     * Creates new form JDlgCdcVendas
     */
    Cdc_ControllerVendasProdutos cdc_ControllerVendasProdutos;
    private boolean incluir; 
    
    public Cdc_jDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Util.habilitar(false, cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal,
                cdc_jBtnConfirmar, cdc_jBtnCancelar, cdc_jBtnIncluirProd, cdc_jBtnAlterarProd, cdc_jBtnExcluirProd);
        Util.habilitar(true, cdc_jBtnIncluir, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jBtnPesquisar);

        ClientesDAO clientesDAO = new ClientesDAO();
            List<CdcClientes> listaClientes = clientesDAO.listAll();
            for (CdcClientes cliente : listaClientes) {
                cdc_jCboClientes.addItem(cliente);
            }

        VendedorDAO vendedorDAO = new VendedorDAO();
            List<CdcVendedor> listaVendedores = vendedorDAO.listAll();
            for (CdcVendedor vendedor : listaVendedores) {
                cdc_jCboVendedor.addItem(vendedor);
        try {
            mascaraDataNasc = new MaskFormatter("##/##/####");
            cdc_jFmtData.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNasc));
        } catch (ParseException ex) {
            Logger.getLogger(Cdc_jDlgUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
            
        cdc_ControllerVendasProdutos = new Cdc_ControllerVendasProdutos();
        cdc_ControllerVendasProdutos.setList(new ArrayList());
        cdc_jTable2.setModel(cdc_ControllerVendasProdutos);
    }

    public CdcVendas viewBean() {
        CdcVendas vendas = new CdcVendas();
        vendas.setCdcIdVendas(Util.strToInt(cdc_jTxtCodigo.getText()));
        
        
        vendas.setCdcClientes((CdcClientes) cdc_jCboVendedor.getSelectedItem());
        vendas.setCdcVendedor((CdcVendedor) cdc_jCboVendedor.getSelectedItem());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    Date dataNasc = formato.parse(cdc_jFmtData.getText());
                    vendas.setCdcDataVenda(dataNasc);
                } catch (ParseException ex) {
                    Logger.getLogger(Cdc_JDlgClientes.class.getName()).log(Level.SEVERE, null, ex);
                }        vendas.setCdcTotal(Util.strToDouble(cdc_jTxtTotal.getText()));
        return vendas;
    }
    
    public void beanView(CdcVendas vendas) {
        cdc_jCboClientes.setSelectedItem(vendas.getCdcClientes());
        cdc_jCboVendedor.setSelectedItem(vendas.getCdcVendedor());
        cdc_jTxtCodigo.setText(Util.intToStr(vendas.getCdcIdVendas()));
            cdc_jTxtTotal.setText(Util.doubleToStr(vendas.getCdcTotal()));
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String dataNasc = formato.format(vendas.getCdcDataVenda());
            cdc_jFmtData.setText(dataNasc);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cdc_jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cdc_jFmtData = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cdc_jCboVendedor = new javax.swing.JComboBox<CdcVendedor>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cdc_jTxtTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        cdc_jTable2 = new javax.swing.JTable();
        cdc_jBtnIncluir = new javax.swing.JButton();
        cdc_jBtnAlterar = new javax.swing.JButton();
        cdc_jBtnExcluir = new javax.swing.JButton();
        cdc_jBtnConfirmar = new javax.swing.JButton();
        cdc_jBtnCancelar = new javax.swing.JButton();
        cdc_jBtnPesquisar = new javax.swing.JButton();
        cdc_jBtnIncluirProd = new javax.swing.JButton();
        cdc_jBtnAlterarProd = new javax.swing.JButton();
        cdc_jBtnExcluirProd = new javax.swing.JButton();
        cdc_jCboClientes = new javax.swing.JComboBox<CdcClientes>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("Data");

        cdc_jFmtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jFmtDataActionPerformed(evt);
            }
        });

        jLabel3.setText("Clientes");

        jLabel4.setText("Vendedor");

        jLabel5.setText("Total");

        cdc_jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(cdc_jTable2);

        cdc_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        cdc_jBtnIncluir.setText("Incluir");
        cdc_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirActionPerformed(evt);
            }
        });

        cdc_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        cdc_jBtnAlterar.setText("Alterar");
        cdc_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnAlterarActionPerformed(evt);
            }
        });

        cdc_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        cdc_jBtnExcluir.setText("Excluir");
        cdc_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnExcluirActionPerformed(evt);
            }
        });

        cdc_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        cdc_jBtnConfirmar.setText("Confirmar");
        cdc_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnConfirmarActionPerformed(evt);
            }
        });

        cdc_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        cdc_jBtnCancelar.setText("Cancelar");
        cdc_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnCancelarActionPerformed(evt);
            }
        });

        cdc_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        cdc_jBtnPesquisar.setText("Pesquisar");
        cdc_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnPesquisarActionPerformed(evt);
            }
        });

        cdc_jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        cdc_jBtnIncluirProd.setToolTipText("");
        cdc_jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirProdActionPerformed(evt);
            }
        });

        cdc_jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        cdc_jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnAlterarProdActionPerformed(evt);
            }
        });

        cdc_jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        cdc_jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnExcluirProdActionPerformed(evt);
            }
        });

        cdc_jCboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jCboClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdc_jBtnAlterarProd)
                            .addComponent(cdc_jBtnIncluirProd)
                            .addComponent(cdc_jBtnExcluirProd)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cdc_jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jCboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdc_jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cdc_jTxtTotal)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cdc_jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnPesquisar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cdc_jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cdc_jCboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cdc_jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cdc_jBtnIncluir)
                            .addComponent(cdc_jBtnAlterar)
                            .addComponent(cdc_jBtnExcluir)
                            .addComponent(cdc_jBtnConfirmar)
                            .addComponent(cdc_jBtnCancelar)
                            .addComponent(cdc_jBtnPesquisar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cdc_jBtnIncluirProd)
                        .addGap(7, 7, 7)
                        .addComponent(cdc_jBtnAlterarProd)
                        .addGap(4, 4, 4)
                        .addComponent(cdc_jBtnExcluirProd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdc_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal,
                cdc_jBtnConfirmar, cdc_jBtnCancelar, cdc_jBtnIncluirProd, cdc_jBtnAlterarProd, cdc_jBtnExcluirProd);
        Util.habilitar(false, cdc_jBtnIncluir, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jBtnPesquisar);
        Util.limpar(cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal);
        cdc_jTxtCodigo.grabFocus();
        incluir = true;
    }//GEN-LAST:event_cdc_jBtnIncluirActionPerformed

    private void cdc_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true,  cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal, cdc_jBtnConfirmar, cdc_jBtnCancelar, cdc_jBtnIncluirProd, cdc_jBtnAlterarProd, cdc_jBtnExcluirProd);
        Util.habilitar(false, cdc_jBtnIncluir, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jBtnPesquisar);
        Util.limpar(cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal);
        cdc_jFmtData.grabFocus();
        incluir = false;
    }//GEN-LAST:event_cdc_jBtnAlterarActionPerformed

    private void cdc_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja Excluir?") == true) {
            Cdc_vendasDAO vendasDAO = new Cdc_vendasDAO();
            vendasDAO.delete(viewBean());
        }
        Util.limpar(cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal);
    }//GEN-LAST:event_cdc_jBtnExcluirActionPerformed

    private void cdc_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        Cdc_vendasDAO vendasDAO = new Cdc_vendasDAO();
        if (incluir == true) {
            vendasDAO.insert(viewBean());
        } else {
            vendasDAO.update(viewBean());
        }
        Util.habilitar(false, cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal,
                cdc_jBtnConfirmar, cdc_jBtnCancelar, cdc_jBtnIncluirProd, cdc_jBtnAlterarProd, cdc_jBtnExcluirProd);
        Util.habilitar(true, cdc_jBtnIncluir, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jBtnPesquisar);
        Util.limpar(cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal);
        
        
        
        
    }//GEN-LAST:event_cdc_jBtnConfirmarActionPerformed

    private void cdc_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal,
                cdc_jBtnConfirmar, cdc_jBtnCancelar, cdc_jBtnIncluirProd, cdc_jBtnAlterarProd, cdc_jBtnExcluirProd);
        Util.habilitar(false, cdc_jBtnIncluir, cdc_jBtnAlterar, cdc_jBtnExcluir, cdc_jBtnPesquisar);
        Util.limpar(cdc_jTxtCodigo, cdc_jFmtData, cdc_jCboClientes, cdc_jCboVendedor, cdc_jTxtTotal);
       
    }//GEN-LAST:event_cdc_jBtnCancelarActionPerformed

    private void cdc_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        Cdc_jDlgVendasPesquisar jDlgVendasPesquisar = new Cdc_jDlgVendasPesquisar(null, true);
        jDlgVendasPesquisar.setTelaPai(this);
        jDlgVendasPesquisar.setVisible(true);
    }//GEN-LAST:event_cdc_jBtnPesquisarActionPerformed

    private void cdc_jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        
        if(Util.perguntar("Deseja Excluir?" )== true ){
            int rowIndex = cdc_jTable2.getSelectedRow();
            cdc_ControllerVendasProdutos.removeBean(rowIndex);
        }
    }//GEN-LAST:event_cdc_jBtnExcluirProdActionPerformed

    private void cdc_jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnAlterarProdActionPerformed
        // TODO add your handling code here:
        Cdc_JDlgVendasProdutos jDlgCdcVendasProdutos = new Cdc_JDlgVendasProdutos(null, true);
        jDlgCdcVendasProdutos.setVisible(true);
    }//GEN-LAST:event_cdc_jBtnAlterarProdActionPerformed

    private void cdc_jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
        Cdc_JDlgVendasProdutos jDlgCdcVendasProdutos = new Cdc_JDlgVendasProdutos(null, true);
        jDlgCdcVendasProdutos.setTelaAnterior(this);
        jDlgCdcVendasProdutos.setVisible(true);
        
        
    }//GEN-LAST:event_cdc_jBtnIncluirProdActionPerformed

    private void cdc_jCboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jCboClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jCboClientesActionPerformed

    private void cdc_jFmtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jFmtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jFmtDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cdc_jDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cdc_jDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cdc_jDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cdc_jDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cdc_jDlgVendas dialog = new Cdc_jDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdc_jBtnAlterar;
    private javax.swing.JButton cdc_jBtnAlterarProd;
    private javax.swing.JButton cdc_jBtnCancelar;
    private javax.swing.JButton cdc_jBtnConfirmar;
    private javax.swing.JButton cdc_jBtnExcluir;
    private javax.swing.JButton cdc_jBtnExcluirProd;
    private javax.swing.JButton cdc_jBtnIncluir;
    private javax.swing.JButton cdc_jBtnIncluirProd;
    private javax.swing.JButton cdc_jBtnPesquisar;
    private javax.swing.JComboBox<CdcClientes> cdc_jCboClientes;
    private javax.swing.JComboBox<CdcVendedor> cdc_jCboVendedor;
    private javax.swing.JFormattedTextField cdc_jFmtData;
    private javax.swing.JTable cdc_jTable2;
    private javax.swing.JTextField cdc_jTxtCodigo;
    private javax.swing.JTextField cdc_jTxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
