/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


/**
 *
 * @author clari
 */
public class Cdc_jDlgVendedor extends javax.swing.JDialog {

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cdc_jLblNome = new javax.swing.JLabel();
        cdc_jTxtNome = new javax.swing.JTextField();
        cdc_jLblCodigo = new javax.swing.JLabel();
        cdc_jTxtCodigo = new javax.swing.JTextField();
        cdc_jLblDataNasc = new javax.swing.JLabel();
        cdc_jLblDataNasc1 = new javax.swing.JLabel();
        cdc_jLblCpf = new javax.swing.JLabel();
        cdc_jLabel1 = new javax.swing.JLabel();
        cdc_jTxtHorasTrabalhadas = new javax.swing.JTextField();
        cdc_jLblAtivo = new javax.swing.JLabel();
        cdc_jBtnIncluir = new javax.swing.JButton();
        cdc_jBtnAlterar = new javax.swing.JButton();
        cdc_jBtnExcluir = new javax.swing.JButton();
        cdc_jBtnConfirmar = new javax.swing.JButton();
        cdc_jBtnCancelar = new javax.swing.JButton();
        cdc_jbtnPesquisar = new javax.swing.JButton();
        cdc_jCBocAtivoSim = new javax.swing.JCheckBox();
        cdc_jFmtdataAdm = new javax.swing.JFormattedTextField();
        cdc_jFmtCpf = new javax.swing.JFormattedTextField();
        cdc_jFmtdataNasc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cdc_jLblNome.setText("Nome");

        cdc_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtNomeActionPerformed(evt);
            }
        });

        cdc_jLblCodigo.setText("Código");

        cdc_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtCodigoActionPerformed(evt);
            }
        });

        cdc_jLblDataNasc.setText("Data de Nascimento");

        cdc_jLblDataNasc1.setText("Data de Admissão");

        cdc_jLblCpf.setText("CPF");

        cdc_jLabel1.setText("Horas Trabalhadas");

        cdc_jTxtHorasTrabalhadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtHorasTrabalhadasActionPerformed(evt);
            }
        });

        cdc_jLblAtivo.setText("Ativo");

        cdc_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        cdc_jBtnIncluir.setText("Incluir");
        cdc_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirActionPerformed(evt);
            }
        });

        cdc_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        cdc_jBtnAlterar.setText("Alterar");
        cdc_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnAlterarActionPerformed(evt);
            }
        });

        cdc_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        cdc_jBtnExcluir.setText("Excluir");
        cdc_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnExcluirActionPerformed(evt);
            }
        });

        cdc_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        cdc_jBtnConfirmar.setText("Confirmar");
        cdc_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnConfirmarActionPerformed(evt);
            }
        });

        cdc_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        cdc_jBtnCancelar.setText("Cancelar");
        cdc_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnCancelarActionPerformed(evt);
            }
        });

        cdc_jbtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        cdc_jbtnPesquisar.setText("Pesquisar");
        cdc_jbtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jbtnPesquisarActionPerformed(evt);
            }
        });

        cdc_jCBocAtivoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jCBocAtivoSimActionPerformed(evt);
            }
        });

        cdc_jFmtdataAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jFmtdataAdmActionPerformed(evt);
            }
        });

        cdc_jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jFmtCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cdc_jBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jBtnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cdc_jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jbtnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cdc_jLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cdc_jLblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cdc_jLblDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cdc_jTxtCodigo)
                                            .addComponent(cdc_jFmtdataNasc))
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cdc_jTxtHorasTrabalhadas)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cdc_jTxtNome)
                                        .addGap(18, 18, 18)
                                        .addComponent(cdc_jCBocAtivoSim)
                                        .addGap(17, 17, 17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cdc_jLblDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cdc_jLblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cdc_jLblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cdc_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cdc_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cdc_jFmtdataAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jLblNome)
                    .addComponent(cdc_jLblAtivo)
                    .addComponent(cdc_jLblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cdc_jCBocAtivoSim)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdc_jLblDataNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdc_jLblCpf)))
                    .addComponent(cdc_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdc_jFmtdataAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdc_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jLblDataNasc)
                    .addComponent(cdc_jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jTxtHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdc_jFmtdataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jBtnIncluir)
                    .addComponent(cdc_jBtnAlterar)
                    .addComponent(cdc_jBtnExcluir)
                    .addComponent(cdc_jBtnConfirmar)
                    .addComponent(cdc_jBtnCancelar)
                    .addComponent(cdc_jbtnPesquisar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdc_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtNomeActionPerformed

    private void cdc_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtCodigoActionPerformed

    private void cdc_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cdc_jBtnIncluirActionPerformed

    private void cdc_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_cdc_jBtnExcluirActionPerformed

    private void cdc_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jBtnConfirmarActionPerformed

    private void cdc_jbtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jbtnPesquisarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jbtnPesquisarActionPerformed

    private void cdc_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jBtnCancelarActionPerformed

    private void cdc_jCBocAtivoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jCBocAtivoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jCBocAtivoSimActionPerformed

    private void cdc_jTxtHorasTrabalhadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtHorasTrabalhadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtHorasTrabalhadasActionPerformed

    private void cdc_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jBtnAlterarActionPerformed

    private void cdc_jFmtdataAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jFmtdataAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jFmtdataAdmActionPerformed

    private void cdc_jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jFmtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jFmtCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdc_jBtnAlterar;
    private javax.swing.JButton cdc_jBtnCancelar;
    private javax.swing.JButton cdc_jBtnConfirmar;
    private javax.swing.JButton cdc_jBtnExcluir;
    private javax.swing.JButton cdc_jBtnIncluir;
    private javax.swing.JCheckBox cdc_jCBocAtivoSim;
    private javax.swing.JFormattedTextField cdc_jFmtCpf;
    private javax.swing.JFormattedTextField cdc_jFmtdataAdm;
    private javax.swing.JFormattedTextField cdc_jFmtdataNasc;
    private javax.swing.JLabel cdc_jLabel1;
    private javax.swing.JLabel cdc_jLblAtivo;
    private javax.swing.JLabel cdc_jLblCodigo;
    private javax.swing.JLabel cdc_jLblCpf;
    private javax.swing.JLabel cdc_jLblDataNasc;
    private javax.swing.JLabel cdc_jLblDataNasc1;
    private javax.swing.JLabel cdc_jLblNome;
    private javax.swing.JTextField cdc_jTxtCodigo;
    private javax.swing.JTextField cdc_jTxtHorasTrabalhadas;
    private javax.swing.JTextField cdc_jTxtNome;
    private javax.swing.JButton cdc_jbtnPesquisar;
    // End of variables declaration//GEN-END:variables
}
