/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import dao.UsuariosDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author clari
 */
public class Cdc_jDlgLogin extends javax.swing.JDialog {
    int contador = 3;

    /**
     * Creates new form Cdc_jDlgLogin
     */
    public Cdc_jDlgLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Tela de Login");
        getContentPane().setBackground(new Color(255,228,225));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cdc_jLblSenha = new javax.swing.JLabel();
        cdc_jLblUsuario = new javax.swing.JLabel();
        cdc_jTxtUsuario = new javax.swing.JTextField();
        cdc_jBtnIncluir = new javax.swing.JButton();
        cdc_jPwdSenha = new javax.swing.JPasswordField();
        cdc_jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cdc_jLblSenha.setText("Senha");

        cdc_jLblUsuario.setText("Usuário");

        cdc_jTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtUsuarioActionPerformed(evt);
            }
        });

        cdc_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        cdc_jBtnIncluir.setText("Fazer Login");
        cdc_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirActionPerformed(evt);
            }
        });

        cdc_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        cdc_jBtnCancelar.setText("Cancelar");
        cdc_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(cdc_jLblUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(cdc_jLblSenha)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cdc_jPwdSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(cdc_jTxtUsuario))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cdc_jBtnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(cdc_jBtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cdc_jLblUsuario)
                .addGap(18, 18, 18)
                .addComponent(cdc_jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cdc_jLblSenha)
                .addGap(18, 18, 18)
                .addComponent(cdc_jPwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cdc_jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cdc_jBtnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdc_jTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtUsuarioActionPerformed

    private void cdc_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirActionPerformed
        // TODO add your handling code here:
//        String usuarioFixo = "cunha";
//        String senhaFixa = "1234";
//        String valorUsuario = cdc_jTxtUsuario.getText();
//        String valorSenha = new String (cdc_jPwdSenha.getPassword());
//        if (valorUsuario.equals(usuarioFixo) && valorSenha.equals(senhaFixa)){
//            Cdc_JFrmPrincipal Cdc_JFrmPrincipal = new Cdc_JFrmPrincipal();
//            Cdc_JFrmPrincipal.setVisible(true);
//            dispose();
//        }else {
//            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos");
//        
        String valorUsuario = cdc_jTxtUsuario.getText();
        String valorSenha = new String(cdc_jPwdSenha.getPassword());

        UsuariosDAO usuarioDAO = new UsuariosDAO();

        boolean login = usuarioDAO.listLogin(valorUsuario, valorSenha);
        if (login) {
            Cdc_JFrmPrincipal JFrmPrincipal = new Cdc_JFrmPrincipal();
            JFrmPrincipal.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "usuario ou senha incorretos");
            contador--;
            if (contador == 0) {
                JOptionPane.showMessageDialog(null, "3 tentativas falhas");
                System.exit(0);
            }
        }

    }//GEN-LAST:event_cdc_jBtnIncluirActionPerformed

    private void cdc_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnCancelarActionPerformed
        // TODO add your handling code hSere:
        dispose();

    }//GEN-LAST:event_cdc_jBtnCancelarActionPerformed
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cdc_jDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cdc_jDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cdc_jDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cdc_jDlgLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cdc_jDlgLogin dialog = new Cdc_jDlgLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdc_jBtnCancelar;
    private javax.swing.JButton cdc_jBtnIncluir;
    private javax.swing.JLabel cdc_jLblSenha;
    private javax.swing.JLabel cdc_jLblUsuario;
    private javax.swing.JPasswordField cdc_jPwdSenha;
    private javax.swing.JTextField cdc_jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
