/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import view.Cdc_JDlgClientes;
import view.Cdc_jDlgUsuario;
import view.Cdc_jDlgVendedor;
import view.Cdc_jDlgVestidos;

/**
 *
 * @author clari
 */
public class Cdc_JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public Cdc_JFrmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Tela Principal");
        getContentPane().setBackground(new Color(255,105,180));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar3 = new javax.swing.JToolBar();
        jBtnFClientes2 = new javax.swing.JButton();
        jBtnFProdutos = new javax.swing.JButton();
        jBtnVendedor = new javax.swing.JButton();
        jBtnFVendas = new javax.swing.JButton();
        jMnuBarra = new javax.swing.JMenuBar();
        jMnuVendedor = new javax.swing.JMenu();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMunVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnuVestidos = new javax.swing.JMenuItem();
        jMnuClientess = new javax.swing.JMenuItem();
        jMnuVendedorr = new javax.swing.JMenuItem();
        jMnuVendass = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar3.setRollover(true);

        jBtnFClientes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        jBtnFClientes2.setFocusable(false);
        jBtnFClientes2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFClientes2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnFClientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFClientes2ActionPerformed(evt);
            }
        });
        jToolBar3.add(jBtnFClientes2);

        jBtnFProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vestido.png"))); // NOI18N
        jBtnFProdutos.setFocusable(false);
        jBtnFProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnFProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFProdutosActionPerformed(evt);
            }
        });
        jToolBar3.add(jBtnFProdutos);

        jBtnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor.png"))); // NOI18N
        jBtnVendedor.setFocusable(false);
        jBtnVendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendedorActionPerformed(evt);
            }
        });
        jToolBar3.add(jBtnVendedor);

        jBtnFVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vender.png"))); // NOI18N
        jBtnFVendas.setFocusable(false);
        jBtnFVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnFVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFVendasActionPerformed(evt);
            }
        });
        jToolBar3.add(jBtnFVendas);

        jMnuVendedor.setText("Cadastros");
        jMnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorActionPerformed(evt);
            }
        });

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDlgClientes(evt);
            }
        });
        jMnuVendedor.add(jMnuClientes);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vestido.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuVendedor.add(jMnuProdutos);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuVendedor.add(jMnuUsuarios);

        jMunVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMunVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor.png"))); // NOI18N
        jMunVendedor.setText("Vendedor");
        jMunVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMunVendedorActionPerformed(evt);
            }
        });
        jMnuVendedor.add(jMunVendedor);
        jMnuVendedor.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuVendedor.add(jMnuSair);

        jMnuBarra.add(jMnuVendedor);

        jMenu1.setText("Movimento");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vender.png"))); // NOI18N
        jMenuItem1.setText("Vendas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMnuBarra.add(jMenu1);

        jMenu2.setText("Consultas");

        jMnuVestidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuVestidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vestido.png"))); // NOI18N
        jMnuVestidos.setText("Vestidos");
        jMnuVestidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVestidosActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuVestidos);

        jMnuClientess.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        jMnuClientess.setText("Clientes");
        jMnuClientess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientessActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuClientess);

        jMnuVendedorr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedorr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor.png"))); // NOI18N
        jMnuVendedorr.setText("Vendedor");
        jMnuVendedorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorrActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuVendedorr);

        jMnuVendass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vender.png"))); // NOI18N
        jMnuVendass.setText("Vendas");
        jMnuVendass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendassActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuVendass);

        jMnuBarra.add(jMenu2);

        setJMenuBar(jMnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        Cdc_jDlgVestidos dlg = new Cdc_jDlgVestidos(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMnuVendedorActionPerformed

    private void jDlgClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDlgClientes
        // TODO add your handling code here:
        Cdc_JDlgClientes dlg = new Cdc_JDlgClientes(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
        
    }//GEN-LAST:event_jDlgClientes

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        Cdc_jDlgUsuario dlg = new Cdc_jDlgUsuario(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMunVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMunVendedorActionPerformed
        // TODO add your handling code here:
        Cdc_jDlgVendedor dlg = new Cdc_jDlgVendedor(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_jMunVendedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Cdc_jDlgVendas dlg = new Cdc_jDlgVendas(this, true); 
        dlg.setLocationRelativeTo(this); 
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBtnFClientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFClientes2ActionPerformed
        // TODO add your handling code here:
        jDlgClientes(null);
        
    }//GEN-LAST:event_jBtnFClientes2ActionPerformed

    private void jBtnFProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFProdutosActionPerformed
        // TODO add your handling code here:
        jMnuProdutosActionPerformed(null);
    }//GEN-LAST:event_jBtnFProdutosActionPerformed

    private void jBtnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendedorActionPerformed
        // TODO add your handling code here:
        jMunVendedorActionPerformed(null);
    }//GEN-LAST:event_jBtnVendedorActionPerformed

    private void jBtnFVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFVendasActionPerformed
        // TODO add your handling code here:
        jMenuItem1ActionPerformed(null);
    }//GEN-LAST:event_jBtnFVendasActionPerformed

    private void jMnuVestidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVestidosActionPerformed
        // TODO add your handling code here:
        Cdc_JDlgConsultaProdutos cdc_JDlgConsultaProdutos = new Cdc_JDlgConsultaProdutos(null, true);
        cdc_JDlgConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuVestidosActionPerformed

    private void jMnuClientessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientessActionPerformed
        // TODO add your handling code here:
        Cdc_JDlgConsultaClientes cdc_JDlgConsultaClientes = new Cdc_JDlgConsultaClientes(null, true);
        cdc_JDlgConsultaClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientessActionPerformed

    private void jMnuVendedorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorrActionPerformed
        // TODO add your handling code here:
        Cdc_JDlgConsultaVendedor cdc_JDlgConsultaVendedor = new Cdc_JDlgConsultaVendedor(null, true);
        cdc_JDlgConsultaVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuVendedorrActionPerformed

    private void jMnuVendassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendassActionPerformed
        // TODO add your handling code here:
        Cdc_JDlgConsultaVendas cdc_JDlgConsultaVendas = new Cdc_JDlgConsultaVendas(null, true);
        cdc_JDlgConsultaVendas.setVisible(true);
    }//GEN-LAST:event_jMnuVendassActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cdc_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cdc_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cdc_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cdc_JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cdc_JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFClientes2;
    private javax.swing.JButton jBtnFProdutos;
    private javax.swing.JButton jBtnFVendas;
    private javax.swing.JButton jBtnVendedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar jMnuBarra;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuClientess;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVendass;
    private javax.swing.JMenu jMnuVendedor;
    private javax.swing.JMenuItem jMnuVendedorr;
    private javax.swing.JMenuItem jMnuVestidos;
    private javax.swing.JMenuItem jMunVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
