/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;



/**
 *
 * @author clari
 */
public class Cdc_jDlgVestidos extends javax.swing.JDialog {
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cdc_JLblNOme = new javax.swing.JLabel();
        cdc_JTxtNome = new javax.swing.JTextField();
        cdc_JLblCodigo = new javax.swing.JLabel();
        cdc_jTxtCodigo = new javax.swing.JTextField();
        cdc_jLblPreco = new javax.swing.JLabel();
        cdc_jTxtPreco = new javax.swing.JTextField();
        cdc_jLblModelo = new javax.swing.JLabel();
        cdc_jLblCategoria = new javax.swing.JLabel();
        cdc_jTxtModelo = new javax.swing.JTextField();
        cdc_jTxtCategoria = new javax.swing.JTextField();
        cdc_jLblMarca = new javax.swing.JLabel();
        cdc_jTxtMarca = new javax.swing.JTextField();
        cdc_jLblAtivo = new javax.swing.JLabel();
        cdc_jCBocAtivo = new javax.swing.JCheckBox();
        cdc_jBtnIncluir = new javax.swing.JButton();
        cdc_jBtnAlterar = new javax.swing.JButton();
        cdc_jBtnExcluir = new javax.swing.JButton();
        cdc_jBtnConfirmar = new javax.swing.JButton();
        cdc_jBtnCancelar = new javax.swing.JButton();
        cdc_jbtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cdc_JLblNOme.setText("Nome");

        cdc_JLblCodigo.setText("Código");

        cdc_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtCodigoActionPerformed(evt);
            }
        });

        cdc_jLblPreco.setText("Preço");

        cdc_jLblModelo.setText("Modelo");

        cdc_jLblCategoria.setText("Categoria");

        cdc_jLblMarca.setText("Marca");

        cdc_jLblAtivo.setText("Ativo");

        cdc_jCBocAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jCBocAtivoActionPerformed(evt);
            }
        });

        cdc_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        cdc_jBtnIncluir.setText("Incluir");
        cdc_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirActionPerformed(evt);
            }
        });

        cdc_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        cdc_jBtnAlterar.setText("Alterar");
        cdc_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnAlterarActionPerformed(evt);
            }
        });

        cdc_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        cdc_jBtnExcluir.setText("Excluir");
        cdc_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnExcluirActionPerformed(evt);
            }
        });

        cdc_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        cdc_jBtnConfirmar.setText("Confirmar");
        cdc_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnConfirmarActionPerformed(evt);
            }
        });

        cdc_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        cdc_jBtnCancelar.setText("Cancelar");
        cdc_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnCancelarActionPerformed(evt);
            }
        });

        cdc_jbtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        cdc_jbtnPesquisar.setText("Pesquisar");
        cdc_jbtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jbtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdc_jTxtPreco)
                            .addComponent(cdc_jTxtCategoria)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jLblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_jLblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdc_JLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cdc_JLblNOme, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cdc_JTxtNome))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cdc_jLblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdc_jLblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdc_jTxtModelo)
                            .addComponent(cdc_jTxtMarca)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(cdc_jCBocAtivo))
                                    .addComponent(cdc_jLblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cdc_jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cdc_jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdc_jbtnPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_JLblCodigo)
                    .addComponent(cdc_jLblAtivo)
                    .addComponent(cdc_JLblNOme))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdc_jCBocAtivo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cdc_JTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jLblPreco)
                    .addComponent(cdc_jLblModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdc_jTxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jLblCategoria)
                    .addComponent(cdc_jLblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jTxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdc_jTxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jBtnIncluir)
                    .addComponent(cdc_jBtnAlterar)
                    .addComponent(cdc_jBtnExcluir)
                    .addComponent(cdc_jBtnConfirmar)
                    .addComponent(cdc_jBtnCancelar)
                    .addComponent(cdc_jbtnPesquisar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdc_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtCodigoActionPerformed

    private void cdc_jCBocAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jCBocAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jCBocAtivoActionPerformed

    private void cdc_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cdc_jBtnIncluirActionPerformed

    private void cdc_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_cdc_jBtnExcluirActionPerformed

    private void cdc_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jBtnConfirmarActionPerformed

    private void cdc_jbtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jbtnPesquisarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jbtnPesquisarActionPerformed

    private void cdc_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jBtnCancelarActionPerformed

    private void cdc_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jBtnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cdc_JLblCodigo;
    private javax.swing.JLabel cdc_JLblNOme;
    private javax.swing.JTextField cdc_JTxtNome;
    private javax.swing.JButton cdc_jBtnAlterar;
    private javax.swing.JButton cdc_jBtnCancelar;
    private javax.swing.JButton cdc_jBtnConfirmar;
    private javax.swing.JButton cdc_jBtnExcluir;
    private javax.swing.JButton cdc_jBtnIncluir;
    private javax.swing.JCheckBox cdc_jCBocAtivo;
    private javax.swing.JLabel cdc_jLblAtivo;
    private javax.swing.JLabel cdc_jLblCategoria;
    private javax.swing.JLabel cdc_jLblMarca;
    private javax.swing.JLabel cdc_jLblModelo;
    private javax.swing.JLabel cdc_jLblPreco;
    private javax.swing.JTextField cdc_jTxtCategoria;
    private javax.swing.JTextField cdc_jTxtCodigo;
    private javax.swing.JTextField cdc_jTxtMarca;
    private javax.swing.JTextField cdc_jTxtModelo;
    private javax.swing.JTextField cdc_jTxtPreco;
    private javax.swing.JButton cdc_jbtnPesquisar;
    // End of variables declaration//GEN-END:variables
}
