/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


/**
 *
 * @author clari
 */
public class Cdc_jDlgUsuario extends javax.swing.JDialog {

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cdc_jLblNome = new javax.swing.JLabel();
        cdc_jTxtNome = new javax.swing.JTextField();
        cdc_JLblCodigo = new javax.swing.JLabel();
        cdc_jTxtCodigo = new javax.swing.JTextField();
        cdc_jLblApelido = new javax.swing.JLabel();
        cdc_jTxtApelido = new javax.swing.JTextField();
        cdc_jLblCpf = new javax.swing.JLabel();
        cdc_JLblDataNasc = new javax.swing.JLabel();
        cdc_JLblNivel = new javax.swing.JLabel();
        cdc_jCboNivel = new javax.swing.JComboBox<>();
        cdc_jLblSenha = new javax.swing.JLabel();
        cdc_jPwdSenha = new javax.swing.JTextField();
        cdc_jBtnIncluir = new javax.swing.JButton();
        cdc_jBtnAlterar = new javax.swing.JButton();
        cdc_jBtnExcluir = new javax.swing.JButton();
        cdc_jBtnConfirmar = new javax.swing.JButton();
        cdc_jBtnPesquisar = new javax.swing.JButton();
        cdc_jLblAtivo = new javax.swing.JLabel();
        cdc_jChbAtivo = new javax.swing.JCheckBox();
        cdc_jBtnCancelar = new javax.swing.JButton();
        cdc_jFmtdataNasci = new javax.swing.JFormattedTextField();
        cdc_jFmtCpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cdc_jLblNome.setText("Nome");

        cdc_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtNomeActionPerformed(evt);
            }
        });

        cdc_JLblCodigo.setText("Código");

        cdc_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jTxtCodigoActionPerformed(evt);
            }
        });

        cdc_jLblApelido.setText("Apelido");

        cdc_jLblCpf.setText("Cpf");

        cdc_JLblDataNasc.setText("Data de Nascimento");

        cdc_JLblNivel.setText("Nível");

        cdc_jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cliente", "Vendedor", "Item 4" }));
        cdc_jCboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jCboNivelActionPerformed(evt);
            }
        });

        cdc_jLblSenha.setText("Senha");

        cdc_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        cdc_jBtnIncluir.setText("Incluir");
        cdc_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnIncluirActionPerformed(evt);
            }
        });

        cdc_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        cdc_jBtnAlterar.setText("Alterar");
        cdc_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnAlterarActionPerformed(evt);
            }
        });

        cdc_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        cdc_jBtnExcluir.setText("Excluir");
        cdc_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnExcluirActionPerformed(evt);
            }
        });

        cdc_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        cdc_jBtnConfirmar.setText("Confirmar");
        cdc_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnConfirmarActionPerformed(evt);
            }
        });

        cdc_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        cdc_jBtnPesquisar.setText("Pesquisar");
        cdc_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnPesquisarActionPerformed(evt);
            }
        });

        cdc_jLblAtivo.setText("Ativo");

        cdc_jChbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jChbAtivoActionPerformed(evt);
            }
        });

        cdc_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        cdc_jBtnCancelar.setText("Cancelar");
        cdc_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdc_jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cdc_jTxtApelido, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cdc_JLblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cdc_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cdc_jLblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addComponent(cdc_jLblApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(cdc_jFmtdataNasci))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(cdc_jLblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(cdc_JLblDataNasc)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cdc_jPwdSenha))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cdc_jBtnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jBtnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cdc_jBtnConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jBtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdc_jBtnPesquisar)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cdc_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cdc_JLblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cdc_jLblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cdc_jTxtNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdc_jLblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cdc_jChbAtivo)))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jLblNome)
                    .addComponent(cdc_JLblCodigo)
                    .addComponent(cdc_jLblAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cdc_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cdc_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cdc_jChbAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdc_JLblDataNasc)
                    .addComponent(cdc_jLblCpf)
                    .addComponent(cdc_JLblNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdc_jFmtdataNasci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdc_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jLblApelido)
                    .addComponent(cdc_jLblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdc_jPwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cdc_jBtnIncluir)
                    .addComponent(cdc_jBtnAlterar)
                    .addComponent(cdc_jBtnExcluir)
                    .addComponent(cdc_jBtnConfirmar)
                    .addComponent(cdc_jBtnPesquisar)
                    .addComponent(cdc_jBtnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdc_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtNomeActionPerformed

    private void cdc_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jTxtCodigoActionPerformed

    private void cdc_jCboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jCboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jCboNivelActionPerformed

    private void cdc_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jBtnIncluirActionPerformed

    private void cdc_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_cdc_jBtnExcluirActionPerformed

    private void cdc_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        
                    
       
    }//GEN-LAST:event_cdc_jBtnConfirmarActionPerformed

    private void cdc_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cdc_jBtnPesquisarActionPerformed

    private void cdc_jChbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jChbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdc_jChbAtivoActionPerformed

    private void cdc_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnAlterarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cdc_jBtnAlterarActionPerformed

    private void cdc_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdc_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cdc_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cdc_JLblCodigo;
    private javax.swing.JLabel cdc_JLblDataNasc;
    private javax.swing.JLabel cdc_JLblNivel;
    private javax.swing.JButton cdc_jBtnAlterar;
    private javax.swing.JButton cdc_jBtnCancelar;
    private javax.swing.JButton cdc_jBtnConfirmar;
    private javax.swing.JButton cdc_jBtnExcluir;
    private javax.swing.JButton cdc_jBtnIncluir;
    private javax.swing.JButton cdc_jBtnPesquisar;
    private javax.swing.JComboBox<String> cdc_jCboNivel;
    private javax.swing.JCheckBox cdc_jChbAtivo;
    private javax.swing.JFormattedTextField cdc_jFmtCpf;
    private javax.swing.JFormattedTextField cdc_jFmtdataNasci;
    private javax.swing.JLabel cdc_jLblApelido;
    private javax.swing.JLabel cdc_jLblAtivo;
    private javax.swing.JLabel cdc_jLblCpf;
    private javax.swing.JLabel cdc_jLblNome;
    private javax.swing.JLabel cdc_jLblSenha;
    private javax.swing.JTextField cdc_jPwdSenha;
    private javax.swing.JTextField cdc_jTxtApelido;
    private javax.swing.JTextField cdc_jTxtCodigo;
    private javax.swing.JTextField cdc_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
