package bean;
// Generated 06/10/2025 20:05:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CdcClientes generated by hbm2java
 */
@Entity
@Table(name="cdc_clientes"
    ,catalog="db_clara_cunha"
)
public class CdcClientes  implements java.io.Serializable {


     private int cdcIdClientes;
     private String cdcNome;
     private String cdcCpf;
     private String cdcRg;
     private String cdcSexo;
     private Date cdcDataNas;
     private String cdcEmail;
     private String cdcCep;
     private String cdcEndereco;
     private String cdcBairro;
     private String cdcEstado;
     private String cdcCidade;
     private String cdcTelefone;
     private String cdcCelular;
     private String cdcAtivo;

    public CdcClientes() {
    }

	
    public CdcClientes(String cdcNome, String cdcCpf, String cdcRg, String cdcCep, String cdcEndereco, String cdcBairro, String cdcEstado, String cdcCidade, String cdcCelular) {
        this.cdcNome = cdcNome;
        this.cdcCpf = cdcCpf;
        this.cdcRg = cdcRg;
        this.cdcCep = cdcCep;
        this.cdcEndereco = cdcEndereco;
        this.cdcBairro = cdcBairro;
        this.cdcEstado = cdcEstado;
        this.cdcCidade = cdcCidade;
        this.cdcCelular = cdcCelular;
    }
    public CdcClientes(String cdcNome, String cdcCpf, String cdcRg, String cdcSexo, Date cdcDataNas, String cdcEmail, String cdcCep, String cdcEndereco, String cdcBairro, String cdcEstado, String cdcCidade, String cdcTelefone, String cdcCelular, String cdcAtivo) {
       this.cdcNome = cdcNome;
       this.cdcCpf = cdcCpf;
       this.cdcRg = cdcRg;
       this.cdcSexo = cdcSexo;
       this.cdcDataNas = cdcDataNas;
       this.cdcEmail = cdcEmail;
       this.cdcCep = cdcCep;
       this.cdcEndereco = cdcEndereco;
       this.cdcBairro = cdcBairro;
       this.cdcEstado = cdcEstado;
       this.cdcCidade = cdcCidade;
       this.cdcTelefone = cdcTelefone;
       this.cdcCelular = cdcCelular;
       this.cdcAtivo = cdcAtivo;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cdc_idClientes", unique=true, nullable=false)
    public int getCdcIdClientes() {
        return this.cdcIdClientes;
    }
    
    public void setCdcIdClientes(int cdcIdClientes) {
        this.cdcIdClientes = cdcIdClientes;
    }

    
    @Column(name="cdc_nome", nullable=false, length=100)
    public String getCdcNome() {
        return this.cdcNome;
    }
    
    public void setCdcNome(String cdcNome) {
        this.cdcNome = cdcNome;
    }

    
    @Column(name="cdc_cpf", nullable=false, length=14)
    public String getCdcCpf() {
        return this.cdcCpf;
    }
    
    public void setCdcCpf(String cdcCpf) {
        this.cdcCpf = cdcCpf;
    }

    
    @Column(name="cdc_rg", nullable=false, length=10)
    public String getCdcRg() {
        return this.cdcRg;
    }
    
    public void setCdcRg(String cdcRg) {
        this.cdcRg = cdcRg;
    }

    
    @Column(name="cdc_sexo", length=1)
    public String getCdcSexo() {
        return this.cdcSexo;
    }
    
    public void setCdcSexo(String cdcSexo) {
        this.cdcSexo = cdcSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cdc_dataNas", length=10)
    public Date getCdcDataNas() {
        return this.cdcDataNas;
    }
    
    public void setCdcDataNas(Date cdcDataNas) {
        this.cdcDataNas = cdcDataNas;
    }

    
    @Column(name="cdc_email", length=70)
    public String getCdcEmail() {
        return this.cdcEmail;
    }
    
    public void setCdcEmail(String cdcEmail) {
        this.cdcEmail = cdcEmail;
    }

    
    @Column(name="cdc_cep", nullable=false, length=9)
    public String getCdcCep() {
        return this.cdcCep;
    }
    
    public void setCdcCep(String cdcCep) {
        this.cdcCep = cdcCep;
    }

    
    @Column(name="cdc_endereco", nullable=false, length=80)
    public String getCdcEndereco() {
        return this.cdcEndereco;
    }
    
    public void setCdcEndereco(String cdcEndereco) {
        this.cdcEndereco = cdcEndereco;
    }

    
    @Column(name="cdc_bairro", nullable=false, length=20)
    public String getCdcBairro() {
        return this.cdcBairro;
    }
    
    public void setCdcBairro(String cdcBairro) {
        this.cdcBairro = cdcBairro;
    }

    
    @Column(name="cdc_estado", nullable=false, length=2)
    public String getCdcEstado() {
        return this.cdcEstado;
    }
    
    public void setCdcEstado(String cdcEstado) {
        this.cdcEstado = cdcEstado;
    }

    
    @Column(name="cdc_cidade", nullable=false, length=30)
    public String getCdcCidade() {
        return this.cdcCidade;
    }
    
    public void setCdcCidade(String cdcCidade) {
        this.cdcCidade = cdcCidade;
    }

    
    @Column(name="cdc_telefone", length=10)
    public String getCdcTelefone() {
        return this.cdcTelefone;
    }
    
    public void setCdcTelefone(String cdcTelefone) {
        this.cdcTelefone = cdcTelefone;
    }

    
    @Column(name="cdc_celular", nullable=false, length=10)
    public String getCdcCelular() {
        return this.cdcCelular;
    }
    
    public void setCdcCelular(String cdcCelular) {
        this.cdcCelular = cdcCelular;
    }

    
    @Column(name="cdc_ativo", length=1)
    public String getCdcAtivo() {
        return this.cdcAtivo;
    }
    
    public void setCdcAtivo(String cdcAtivo) {
        this.cdcAtivo = cdcAtivo;
    }






}


