package bean;
// Generated 06/10/2025 20:05:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CdcUsuario generated by hbm2java
 */
@Entity
@Table(name="cdc_usuario"
    ,catalog="db_clara_cunha"
)
public class CdcUsuario  implements java.io.Serializable {


     private Integer cdcIdUsuario;
     private String cdcNome;
     private String cdcApelido;
     private String cdcCpf;
     private Date cdcDataNas;
     private String cdcSenha;
     private int cdcNivel;
     private String cdcAtivo;
     private Set cdcVendases = new HashSet(0);

    public CdcUsuario() {
    }

	
    public CdcUsuario(String cdcNome, String cdcApelido, String cdcCpf, String cdcSenha, int cdcNivel) {
        this.cdcNome = cdcNome;
        this.cdcApelido = cdcApelido;
        this.cdcCpf = cdcCpf;
        this.cdcSenha = cdcSenha;
        this.cdcNivel = cdcNivel;
    }
    public CdcUsuario(String cdcNome, String cdcApelido, String cdcCpf, Date cdcDataNas, String cdcSenha, int cdcNivel, String cdcAtivo, Set cdcVendases) {
       this.cdcNome = cdcNome;
       this.cdcApelido = cdcApelido;
       this.cdcCpf = cdcCpf;
       this.cdcDataNas = cdcDataNas;
       this.cdcSenha = cdcSenha;
       this.cdcNivel = cdcNivel;
       this.cdcAtivo = cdcAtivo;
       this.cdcVendases = cdcVendases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cdc_idUsuario", unique=true, nullable=false)
    public Integer getCdcIdUsuario() {
        return this.cdcIdUsuario;
    }
    
    public void setCdcIdUsuario(Integer cdcIdUsuario) {
        this.cdcIdUsuario = cdcIdUsuario;
    }

    
    @Column(name="cdc_nome", nullable=false, length=40)
    public String getCdcNome() {
        return this.cdcNome;
    }
    
    public void setCdcNome(String cdcNome) {
        this.cdcNome = cdcNome;
    }

    
    @Column(name="cdc_apelido", nullable=false, length=25)
    public String getCdcApelido() {
        return this.cdcApelido;
    }
    
    public void setCdcApelido(String cdcApelido) {
        this.cdcApelido = cdcApelido;
    }

    
    @Column(name="cdc_cpf", nullable=false, length=14)
    public String getCdcCpf() {
        return this.cdcCpf;
    }
    
    public void setCdcCpf(String cdcCpf) {
        this.cdcCpf = cdcCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cdc_dataNas", length=10)
    public Date getCdcDataNas() {
        return this.cdcDataNas;
    }
    
    public void setCdcDataNas(Date cdcDataNas) {
        this.cdcDataNas = cdcDataNas;
    }

    
    @Column(name="cdc_senha", nullable=false, length=20)
    public String getCdcSenha() {
        return this.cdcSenha;
    }
    
    public void setCdcSenha(String cdcSenha) {
        this.cdcSenha = cdcSenha;
    }

    
    @Column(name="cdc_nivel", nullable=false)
    public int getCdcNivel() {
        return this.cdcNivel;
    }
    
    public void setCdcNivel(int cdcNivel) {
        this.cdcNivel = cdcNivel;
    }

    
    @Column(name="cdc_ativo", length=1)
    public String getCdcAtivo() {
        return this.cdcAtivo;
    }
    
    public void setCdcAtivo(String cdcAtivo) {
        this.cdcAtivo = cdcAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cdcUsuario")
    public Set getCdcVendases() {
        return this.cdcVendases;
    }
    
    public void setCdcVendases(Set cdcVendases) {
        this.cdcVendases = cdcVendases;
    }




}


