package bean;
// Generated 06/10/2025 20:05:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CdcVendas generated by hbm2java
 */
@Entity
@Table(name="cdc_vendas"
    ,catalog="db_clara_cunha"
)
public class CdcVendas  implements java.io.Serializable {


     private int cdcIdVendas;
     private CdcClientes cdcClientes;
     private CdcVendedor cdcVendedor;
     private Date cdcDataVenda;
     private String cdcStatus;
     private String cdcFormaPaga;
     private double cdcTotal;
     private Set cdcVendasProdutoses = new HashSet(0);

    public CdcVendas() {
    }

	
    public CdcVendas(CdcClientes cdcClientes, CdcVendedor cdcVendedor, String cdcStatus, String cdcFormaPaga, double cdcTotal) {
        this.cdcClientes = cdcClientes;
        this.cdcVendedor = cdcVendedor;
        this.cdcStatus = cdcStatus;
        this.cdcFormaPaga = cdcFormaPaga;
        this.cdcTotal = cdcTotal;
    }
    public CdcVendas(CdcClientes cdcClientes, CdcVendedor cdcVendedor, Date cdcDataVenda, String cdcStatus, String cdcFormaPaga, double cdcTotal) {
       this.cdcClientes = cdcClientes;
       this.cdcVendedor = cdcVendedor;
       this.cdcDataVenda = cdcDataVenda;
       this.cdcStatus = cdcStatus;
       this.cdcFormaPaga = cdcFormaPaga;
       this.cdcTotal = cdcTotal;
       this.cdcVendasProdutoses = cdcVendasProdutoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cdc_idVendas", unique=true, nullable=false)
    public int getCdcIdVendas() {
        return this.cdcIdVendas;
    }
    
    public void setCdcIdVendas(int cdcIdVendas) {
        this.cdcIdVendas = cdcIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cdc_idClientes", nullable=false)
    public CdcClientes getCdcClientes() {
        return this.cdcClientes;
    }
    
    public void setCdcClientes(CdcClientes cdcClientes) {
        this.cdcClientes = cdcClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cdc_idVendedor", nullable=false)
    public CdcVendedor getCdcVendedor() {
        return this.cdcVendedor;
    }
    
    public void setCdcVendedor(CdcVendedor cdcVendedor) {
        this.cdcVendedor = cdcVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cdc_dataVenda", length=10)
    public Date getCdcDataVenda() {
        return this.cdcDataVenda;
    }
    
    public void setCdcDataVenda(Date cdcDataVenda) {
        this.cdcDataVenda = cdcDataVenda;
    }

    
    @Column(name="cdc_status", nullable=false, length=12)
    public String getCdcStatus() {
        return this.cdcStatus;
    }
    
    public void setCdcStatus(String cdcStatus) {
        this.cdcStatus = cdcStatus;
    }

    
    @Column(name="cdc_formaPaga", nullable=false, length=30)
    public String getCdcFormaPaga() {
        return this.cdcFormaPaga;
    }
    
    public void setCdcFormaPaga(String cdcFormaPaga) {
        this.cdcFormaPaga = cdcFormaPaga;
    }

    
    @Column(name="cdc_total", nullable=false, precision=10)
    public double getCdcTotal() {
        return this.cdcTotal;
    }
    
    public void setCdcTotal(double cdcTotal) {
        this.cdcTotal = cdcTotal;
    }






}


