package bean;
// Generated 06/10/2025 20:05:40 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CdcVendas generated by hbm2java
 */
@Entity
@Table(name="cdc_vendas"
    ,catalog="db_clara_cunha"
)
public class CdcVendas  implements java.io.Serializable {


     private Integer cdcIdVendas;
     private CdcClientes cdcClientes;
     private CdcUsuario cdcUsuario;
     private Date cdcDataVenda;
     private String cdcStatus;
     private String cdcFormaPaga;
     private BigDecimal cdcTotal;
     private Set cdcVendasProdutoses = new HashSet(0);

    public CdcVendas() {
    }

	
    public CdcVendas(CdcClientes cdcClientes, CdcUsuario cdcUsuario, String cdcStatus, String cdcFormaPaga, BigDecimal cdcTotal) {
        this.cdcClientes = cdcClientes;
        this.cdcUsuario = cdcUsuario;
        this.cdcStatus = cdcStatus;
        this.cdcFormaPaga = cdcFormaPaga;
        this.cdcTotal = cdcTotal;
    }
    public CdcVendas(CdcClientes cdcClientes, CdcUsuario cdcUsuario, Date cdcDataVenda, String cdcStatus, String cdcFormaPaga, BigDecimal cdcTotal, Set cdcVendasProdutoses) {
       this.cdcClientes = cdcClientes;
       this.cdcUsuario = cdcUsuario;
       this.cdcDataVenda = cdcDataVenda;
       this.cdcStatus = cdcStatus;
       this.cdcFormaPaga = cdcFormaPaga;
       this.cdcTotal = cdcTotal;
       this.cdcVendasProdutoses = cdcVendasProdutoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cdc_idVendas", unique=true, nullable=false)
    public Integer getCdcIdVendas() {
        return this.cdcIdVendas;
    }
    
    public void setCdcIdVendas(Integer cdcIdVendas) {
        this.cdcIdVendas = cdcIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cdc_idClientes", nullable=false)
    public CdcClientes getCdcClientes() {
        return this.cdcClientes;
    }
    
    public void setCdcClientes(CdcClientes cdcClientes) {
        this.cdcClientes = cdcClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cdc_idVendedor", nullable=false)
    public CdcUsuario getCdcUsuario() {
        return this.cdcUsuario;
    }
    
    public void setCdcUsuario(CdcUsuario cdcUsuario) {
        this.cdcUsuario = cdcUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cdc_dataVenda", length=10)
    public Date getCdcDataVenda() {
        return this.cdcDataVenda;
    }
    
    public void setCdcDataVenda(Date cdcDataVenda) {
        this.cdcDataVenda = cdcDataVenda;
    }

    
    @Column(name="cdc_status", nullable=false, length=12)
    public String getCdcStatus() {
        return this.cdcStatus;
    }
    
    public void setCdcStatus(String cdcStatus) {
        this.cdcStatus = cdcStatus;
    }

    
    @Column(name="cdc_formaPaga", nullable=false, length=30)
    public String getCdcFormaPaga() {
        return this.cdcFormaPaga;
    }
    
    public void setCdcFormaPaga(String cdcFormaPaga) {
        this.cdcFormaPaga = cdcFormaPaga;
    }

    
    @Column(name="cdc_total", nullable=false, precision=10)
    public BigDecimal getCdcTotal() {
        return this.cdcTotal;
    }
    
    public void setCdcTotal(BigDecimal cdcTotal) {
        this.cdcTotal = cdcTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cdcVendas")
    public Set getCdcVendasProdutoses() {
        return this.cdcVendasProdutoses;
    }
    
    public void setCdcVendasProdutoses(Set cdcVendasProdutoses) {
        this.cdcVendasProdutoses = cdcVendasProdutoses;
    }




}


