package bean;
// Generated 06/10/2025 20:05:40 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CdcVendedor generated by hbm2java
 */
@Entity
@Table(name="cdc_vendedor"
    ,catalog="db_clara_cunha"
)
public class CdcVendedor  implements java.io.Serializable {


     private int cdcIdVendedor;
     private String cdcNome;
     private String cdcCpf;
     private Date cdcDataNas;
     private Date cdcDataAdmissao;
     private Date cdcHorasTrab;
     private String cdcAtivo;

    public CdcVendedor() {
    }

	
    public CdcVendedor(String cdcNome, String cdcCpf, Date cdcHorasTrab) {
        this.cdcNome = cdcNome;
        this.cdcCpf = cdcCpf;
        this.cdcHorasTrab = cdcHorasTrab;
    }
    public CdcVendedor(String cdcNome, String cdcCpf, Date cdcDataNas, Date cdcDataAdmissao, Date cdcHorasTrab, String cdcAtivo) {
       this.cdcNome = cdcNome;
       this.cdcCpf = cdcCpf;
       this.cdcDataNas = cdcDataNas;
       this.cdcDataAdmissao = cdcDataAdmissao;
       this.cdcHorasTrab = cdcHorasTrab;
       this.cdcAtivo = cdcAtivo;
    }
   
     @Id 

    
    @Column(name="cdc_idVendedor", unique=true, nullable=false)
    public int getCdcIdVendedor() {
        return this.cdcIdVendedor;
    }
    
    public void setCdcIdVendedor(int cdcIdVendedor) {
        this.cdcIdVendedor = cdcIdVendedor;
    }

    
    @Column(name="cdc_nome", nullable=false, length=40)
    public String getCdcNome() {
        return this.cdcNome;
    }
    
    public void setCdcNome(String cdcNome) {
        this.cdcNome = cdcNome;
    }

    
    @Column(name="cdc_cpf", nullable=false, length=14)
    public String getCdcCpf() {
        return this.cdcCpf;
    }
    
    public void setCdcCpf(String cdcCpf) {
        this.cdcCpf = cdcCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cdc_dataNas", length=10)
    public Date getCdcDataNas() {
        return this.cdcDataNas;
    }
    
    public void setCdcDataNas(Date cdcDataNas) {
        this.cdcDataNas = cdcDataNas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cdc_dataAdmissao", length=10)
    public Date getCdcDataAdmissao() {
        return this.cdcDataAdmissao;
    }
    
    public void setCdcDataAdmissao(Date cdcDataAdmissao) {
        this.cdcDataAdmissao = cdcDataAdmissao;
    }

    
    @Column(name="cdc_horasTrab", nullable=true)
    public Date getCdcHorasTrab() {
        return this.cdcHorasTrab;
    }
    
    public void setCdcHorasTrab(Date cdcHorasTrab) {
        this.cdcHorasTrab = cdcHorasTrab;
    }

    
    @Column(name="cdc_ativo", length=1)
    public String getCdcAtivo() {
        return this.cdcAtivo;
    }
    
    public void setCdcAtivo(String cdcAtivo) {
        this.cdcAtivo = cdcAtivo;
    }
    @Override
    public String toString(){
        return this.cdcNome;
    }
    
     @Override
    public boolean equals(Object object){
        if (object instanceof CdcVendedor){
            CdcVendedor cdcVendedor = (CdcVendedor)object;
            if (this.getCdcIdVendedor() == cdcVendedor.getCdcIdVendedor()){
                return true;
            }
        }
         return false;
    }



}


