package bean;
// Generated 06/10/2025 20:05:40 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CdcVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="cdc_vendas_produtos"
    ,catalog="db_clara_cunha"
)
public class CdcVendasProdutos  implements java.io.Serializable {


     private Integer cdcIdVendasProdutos;
     private CdcVendas cdcVendas;
     private CdcVestidos cdcVestidos;
     private double cdcValorUnitario;
     private int cdcQuantidade;

    public CdcVendasProdutos() {
    }

    public CdcVendasProdutos(CdcVendas cdcVendas, CdcVestidos cdcVestidos, double cdcValorUnitario, int cdcQuantidade) {
       this.cdcVendas = cdcVendas;
       this.cdcVestidos = cdcVestidos;
       this.cdcValorUnitario = cdcValorUnitario;
       this.cdcQuantidade = cdcQuantidade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cdc_idVendasProdutos", unique=true, nullable=false)
    public Integer getCdcIdVendasProdutos() {
        return this.cdcIdVendasProdutos;
    }
    
    public void setCdcIdVendasProdutos(Integer cdcIdVendasProdutos) {
        this.cdcIdVendasProdutos = cdcIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cdc_idVendas", nullable=false)
    public CdcVendas getCdcVendas() {
        return this.cdcVendas;
    }
    
    public void setCdcVendas(CdcVendas cdcVendas) {
        this.cdcVendas = cdcVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cdc_idVestidos", nullable=false)
    public CdcVestidos getCdcVestidos() {
        return this.cdcVestidos;
    }
    
    public void setCdcVestidos(CdcVestidos cdcVestidos) {
        this.cdcVestidos = cdcVestidos;
    }

    
    @Column(name="cdc_valorUnitario", nullable=false, precision=10)
    public double getCdcValorUnitario() {
        return this.cdcValorUnitario;
    }
    
    public void setCdcValorUnitario(double cdcValorUnitario) {
        this.cdcValorUnitario = cdcValorUnitario;
    }

    
    @Column(name="cdc_quantidade", nullable=false)
    public int getCdcQuantidade() {
        return this.cdcQuantidade;
    }
    
    public void setCdcQuantidade(int cdcQuantidade) {
        this.cdcQuantidade = cdcQuantidade;
    }




}


