package bean;
// Generated 06/10/2025 20:05:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CdcVestidos generated by hbm2java
 */
@Entity
@Table(name="cdc_vestidos"
    ,catalog="db_clara_cunha"
)
public class CdcVestidos  implements java.io.Serializable {


     private int cdcIdVestidos;
     private String cdcNome;
     private double cdcPreco;
     private String cdcModelo;
     private String cdcCategoria;
     private String cdcMarca;
     private String cdcAtivo;
   
    public CdcVestidos() {
    }

	
    public CdcVestidos(String cdcNome, String cdcAtivo) {
        this.cdcNome = cdcNome;
        this.cdcAtivo = cdcAtivo;
    }
    public CdcVestidos(String cdcNome, double cdcPreco, String cdcModelo, String cdcCategoria, String cdcMarca, String cdcAtivo) {
       this.cdcNome = cdcNome;
       this.cdcPreco = cdcPreco;
       this.cdcModelo = cdcModelo;
       this.cdcCategoria = cdcCategoria;
       this.cdcMarca = cdcMarca;
       this.cdcAtivo = cdcAtivo;
    }
   
     @Id 

    
    @Column(name="cdc_idVestidos", unique=true, nullable=false)
    public int getCdcIdVestidos() {
        return this.cdcIdVestidos;
    }
    
    public void setCdcIdVestidos(int cdcIdVestidos) {
        this.cdcIdVestidos = cdcIdVestidos;
    }

    
    @Column(name="cdc_nome", nullable=false, length=60)
    public String getCdcNome() {
        return this.cdcNome;
    }
    
    public void setCdcNome(String cdcNome) {
        this.cdcNome = cdcNome;
    }

    
    @Column(name="cdc_preco", precision=10)
    public double getCdcPreco() {
        return this.cdcPreco;
    }
    
    public void setCdcPreco(double cdcPreco) {
        this.cdcPreco = cdcPreco;
    }

    
    @Column(name="cdc_modelo", length=30)
    public String getCdcModelo() {
        return this.cdcModelo;
    }
    
    public void setCdcModelo(String cdcModelo) {
        this.cdcModelo = cdcModelo;
    }

    
    @Column(name="cdc_categoria", length=30)
    public String getCdcCategoria() {
        return this.cdcCategoria;
    }
    
    public void setCdcCategoria(String cdcCategoria) {
        this.cdcCategoria = cdcCategoria;
    }

    
    @Column(name="cdc_marca", length=40)
    public String getCdcMarca() {
        return this.cdcMarca;
    }
    
    public void setCdcMarca(String cdcMarca) {
        this.cdcMarca = cdcMarca;
    }

    
    @Column(name="cdc_ativo", nullable=false, length=1)
    public String getCdcAtivo() {
        return this.cdcAtivo;
    }
    
    public void setCdcAtivo(String cdcAtivo) {
        this.cdcAtivo = cdcAtivo;
    }
     @Override
    public String toString(){
        return this.cdcNome;
    }
     @Override
            public boolean equals(Object object){
        if (object instanceof CdcVestidos){
            CdcVestidos vestidos = (CdcVestidos)object;
            if (this.getCdcIdVestidos()== vestidos.getCdcIdVestidos()){
                return true;
            }
        }
         return false;
    }





}


